### ISSUE TITLE
Android build failure with react-native 0.31

### ISSUE THREAD

**Issue by varungupta85** [bamlab/react-native-image-resizer#30]
I get the following error while running `react-native run-android` command in the my app after including the library. If I remove the library, then the application runs without errors. Also, I noticed that the when I ran the `rnpm link` command, it updated the `MainActivity.java` file instead of the `MainApplication.java` file. I guess the library has not been updated according to the changes introduced in `react-native 0.29`

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Landroid/support/v7/appcompat/R$anim;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

**Comment by 4ian** [comment]
Same thing for me while creating a new project with React Native 0.31, but I've been able to fix that just by running: `cd android && ./gradlew clean`.
Not sure why it was needed. Let me know if this works and if it's the case I'll add a troubleshooting section to the README with this :)
