### ISSUE TITLE
App crashing on Android device while taking picture

### ISSUE THREAD

**Issue by Joshig99** [bamlab/react-native-image-resizer#305]
Caused by java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.<init>(Uri.java:507)
       at android.net.Uri$StringUri.<init>(Uri.java:497)
       at android.net.Uri.parse(Uri.java:469)
       at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImageWithExceptions(ImageResizerModule.java:79)
       at fr.bamlab.rnimageresizer.ImageResizerModule.access$000(ImageResizerModule.java:27)
       at fr.bamlab.rnimageresizer.ImageResizerModule$1.doInBackgroundGuarded(ImageResizerModule.java:63)
       at fr.bamlab.rnimageresizer.ImageResizerModule$1.doInBackgroundGuarded(ImageResizerModule.java:59)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:36)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:20)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
       
Android : 12
react-native-image-resizer :1.4.5
react-native: 0.64.0

**Comment by CaCaBlocker** [comment]
![image](https://user-images.githubusercontent.com/87882515/168993415-6c45264d-8d67-435e-80e9-1cf34f679a64.png)

"react": "17.0.2",
"react-native": "0.67.2"

I had same issue. Any solution to fix it?

**Comment by chaudhary** [comment]
I am facing the same issue
