### ISSUE TITLE
Breaking change in v3.0.5 to v3.0.6

### ISSUE THREAD

**Issue by laurent22** [bamlab/react-native-image-resizer#385]
I assume this is a patch release but at least for us it no longer builds, probably due to some breaking change on the TypeScript types.

Renovate PR is there: https://github.com/laurent22/joplin/pull/8832

```
2023-09-11T10:39:24.4540948Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR Error: [tsl] ERROR in /home/runner/work/joplin/joplin/packages/app-mobile/components/screens/Note.tsx(39,26)
2023-09-11T10:39:24.4565404Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR TS7016: Could not find a declaration file for module '@bam.tech/react-native-image-resizer'. '/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/@bam.tech/react-native-image-resizer/lib/commonjs/index.js' implicitly has an 'any' type.
2023-09-11T10:39:24.4579773Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR Try `npm i --save-dev @types/bam.tech__react-native-image-resizer` if it exists or add a new declaration (.d.ts) file containing `declare module '@bam.tech/react-native-image-resizer';`
2023-09-11T10:39:24.4599901Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at makeError (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/ts-loader/dist/utils.js:93:19)
2023-09-11T10:39:24.4621114Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at /home/runner/work/joplin/joplin/packages/app-mobile/node_modules/ts-loader/dist/utils.js:63:27
2023-09-11T10:39:24.4633009Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at Array.map ()
2023-09-11T10:39:24.4649616Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at formatErrors (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/ts-loader/dist/utils.js:46:14)
2023-09-11T10:39:24.4657501Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at provideErrorsToWebpack (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/ts-loader/dist/after-compile.js:167:62)
2023-09-11T10:39:24.4672369Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at /home/runner/work/joplin/joplin/packages/app-mobile/node_modules/ts-loader/dist/after-compile.js:36:9
2023-09-11T10:39:24.4684250Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at /home/runner/work/joplin/joplin/packages/app-mobile/node_modules/ts-loader/dist/instances.js:206:13
2023-09-11T10:39:24.4696402Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at fn (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/webpack/lib/Compilation.js:478:10)
2023-09-11T10:39:24.4710643Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at Hook.eval [as callAsync] (eval at create (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/tapable/lib/HookCodeFactory.js:33:10), :38:1)
2023-09-11T10:39:24.4725166Z ➤ YN0000: │ @joplin/app-mobile@workspace:packages/app-mobile STDERR at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/runner/work/joplin/joplin/packages/app-mobile/node_modules/tapable/lib/Hook.js:18:14)
```

**Comment by laurent22** [comment]
I see it's been fixed here, sorry for the double report! https://github.com/bamlab/react-native-image-resizer/issues/383 Looks like Renovate doesn't pick up 3.0.7 for some reason so it's a different issue anyway
