### ISSUE TITLE
Could not invoke ImageResizerAndroid exception

### ISSUE THREAD

**Issue by holyxiaoxin** [bamlab/react-native-image-resizer#44]
JPEG works well, but when trying to compress PNG format, it throws:

```
Could not invoke ImageResizerAndroid.createResizedImage
```

exception.

Tried setting the compressFormat to both `JPEG` and `PNG`, but didn't work.

**Comment by burnoutberni** [comment]
same error here, but only on certain devices, it still works on the Android devices of my co-workers.

**Comment by 4ian** [comment]
It's quite probable that an exception (in the Java part) was thrown while doing the resizing. Could you check the logs of your device and paste them here?

**Comment by jasongaare** [comment]
Not sure how beneficial this is. Working on finding what's throwing the error.

    java.lang.RuntimeException: Could not invoke ImageResizerAndroud.createResizedImage
      at fr.bamlab.rnimageresizer.ImageResizer.loadBitmap(ImageResizer.java:195)
      at fr.bamlab.rnimageresizer.ImageResizer.loadBitmapFromFile(ImageResizer.java:221)
      at fr.bamlab.rnimageresizer.ImageResizer.createResizedImage(ImageResizer.java:261)
      at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImageWithExceptions(ImageResizerModule.java:52)
      at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImage(ImageResizerModule.java:37)

**Comment by holyxiaoxin** [comment]
I'm also experiencing this problem. Might be related to storage issues. It only happen to a specific group of users.

```
Fatal Exception: java.lang.RuntimeException: Could not invoke ImageResizerAndroid.createResizedImage
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:333)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.OutOfMemoryError: Failed to allocate a 51916812 byte allocation with 16777216 free bytes and 37MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:739)
       at fr.bamlab.rnimageresizer.ImageResizer.rotateImage(ImageResizer.java:66)
       at fr.bamlab.rnimageresizer.ImageResizer.createResizedImage(ImageResizer.java:281)
       at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImageWithExceptions(ImageResizerModule.java:52)
       at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImage(ImageResizerModule.java:37)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by tommynordli** [comment]
Same here, and it's only happening on a few Samsung devices. 70% of the crashes is coming from SM-G900F (Samsung Galaxy S5).

`
java.lang.OutOfMemoryError: Failed to allocate a 19660812 byte allocation with 5475880 free bytes and 5MB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
    at android.graphics.Bitmap.nativeCreate(Bitmap.java)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
    at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:753)
    at fr.bamlab.rnimageresizer.ImageResizer.resizeImage(ImageResizer.java:48)
    at fr.bamlab.rnimageresizer.ImageResizer.createResizedImage(ImageResizer.java:277)
    at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImageWithExceptions(ImageResizerModule.java:54)
    at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImage(ImageResizerModule.java:41)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:158)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:818)
java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:158)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:818)
java.lang.RuntimeException: Could not invoke ImageResizerAndroid.createResizedImage
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:385)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:158)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:818)
`

**Comment by tommynordli** [comment]
Allowing largeHeap fixed this for me, but I wish there was another solution that didn't include settings largeHeap to true

´´´
<application
    ....
    android:largeHeap="true"> 
´´´
