### ISSUE TITLE
NPE in 0.0.12

### ISSUE THREAD

**Issue by npomfret** [bamlab/react-native-image-resizer#54]
```
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   java.lang.NullPointerException
                                                       at fr.bamlab.rnimageresizer.ImageResizer.rotateImage(ImageResizer.java:63)
                                                       at fr.bamlab.rnimageresizer.ImageResizer.createResizedImage(ImageResizer.java:231)
                                                       at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImageWithExceptions(ImageResizerModule.java:49)
                                                       at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImage(ImageResizerModule.java:37)
```

**Comment by PierreCapo** [comment]
Closed as staled issue with old version of React-Native or react-native-image-resizer.
