### ISSUE TITLE
Invalid crop rectangle: [0, -473, 360, 473]

### ISSUE THREAD

**Issue by sibelius** [bamlab/react-native-image-resizer#65]
```java
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Invalid crop rectangle: [0, -473, 360, 473]
       at com.facebook.react.modules.camera.ImageEditingManager$CropTask.<init>(ImageEditingManager.java:222)
       at com.facebook.react.modules.camera.ImageEditingManager$CropTask.<init>(ImageEditingManager.java:199)
       at com.facebook.react.modules.camera.ImageEditingManager.cropImage(ImageEditingManager.java:189)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by sibelius** [comment]
fixing added a try catch
