### ISSUE TITLE
Crash due to out of memory error which trying to compress image using createResizedImage

### ISSUE THREAD

**Issue by bdipak** [bamlab/react-native-image-resizer#97]
While trying to resize large image of size around 5MB, there is an out of memory exception on some lower end phones with low memory. Out of memory exception in this case is expected but it should be gracefully handled instead of crashing the application.

Shouldn't it try to catch all such out of memory exceptions and throw resize error exception to caller? Since it is crashing my app, I am not able to use it in our production app. Please see if you can consider this.

**Comment by 4ian** [comment]
Such exception should indeed be catched and reported properly. If anyone is able to do it, I'll merge the PR so that the next version is protected against this.

**Comment by freiserg** [comment]
@4ian StackTrace such crach:

```
java.lang.OutOfMemoryError: Failed to allocate a 2430012 byte allocation with 1305354 free bytes and 1274KB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
    at android.graphics.Bitmap.nativeCreate(Bitmap.java)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
    at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:724)
    at fr.bamlab.rnimageresizer.ImageResizer.resizeImage(ImageResizer.java:53)
    at fr.bamlab.rnimageresizer.ImageResizer.createResizedImage(ImageResizer.java:283)
    at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImageWithExceptions(ImageResizerModule.java:52)
    at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImage(ImageResizerModule.java:37)
```

It try to catch only IOException exceptions [link to code](https://github.com/bamlab/react-native-image-resizer/blame/master/android/src/main/java/fr/bamlab/rnimageresizer/ImageResizerModule.java#L43)

Shouldn't it try to catch all exceptions?

**Comment by holyxiaoxin** [comment]
And also, to add on, you can increase your memory heap by setting: 
`android:largeHeap="true"` in manifest file:

https://stackoverflow.com/questions/32244851/androidjava-lang-outofmemoryerror-failed-to-allocate-a-23970828-byte-allocatio

This reduces the chance of having OOM error thrown when dealing with large bitmaps.

**Comment by viju85** [comment]
I am seeing the same crash with below stacktrace:
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 110806760 byte allocation with 33554432 free bytes and 37MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:663)
	at fr.bamlab.rnimageresizer.a.a(SourceFile:2048)
	at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImageWithExceptions(SourceFile:54)
	at fr.bamlab.rnimageresizer.ImageResizerModule.createResizedImage(SourceFile:41)

**Comment by shehzadosama** [comment]
This solution worked for me.
1. Adding following in android/app/build.gradle:

`android {
    ...
    dexOptions { javaMaxHeapSize "2g" }
    ...
    }`

2. Adding following in android/gradle.properties:

`org.gradle.jvmargs=-Xmx4608M`
